require("mason-lspconfig").setup {
    ensure_installed = {
        "lua_ls",
        "ruff",
        "ty",
        "pyright",
        "ltex",
        "clangd",
        "autotools_ls",
        "tailwindcss",
        "docker_language_server",
        "java_language_server",
        "jinja_lsp",
        "jsonls",
        "marksman",
        "codebook",
        "gitlab_ci_ls",
    },
    automatic_enable = false,
}
